---
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
ansible_python_interpreter: '/usr/bin/python2.7'
dnsNameServers:
  - 10.100.10.1

ntp_area: 'us'
ntp_servers: 
  - ntp.rz.lab

rsyslog_server: syslog.rz.lab

netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses:
            - 10.100.10.1

systemd_resolved:
  disabled: true
  nameservers:
    - 10.100.10.1
  search_zones:
    - rz.lab

docker:
  compose:
    version: 1.23.1
    checksum: "sha256:c176543737b8aea762022245f0f4d58781d3cb1b072bc14f3f8e5bb96f90f1a2"
  repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  package: docker-ce=17.03.3~ce-0~ubuntu-xenial
  users:
    - vagrant