---
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
ansible_python_interpreter: '/usr/bin/python2.7'
dnsNameServers:
  - 10.100.10.1

ntp_area: 'us'
ntp_servers: 
  - ntp.rz.lab

rsyslog_server: syslog.rz.lab

netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses:
            - 10.100.10.1

systemd_resolved:
  disabled: true
  nameservers:
    - 10.100.10.1
  search_zones:
    - rz.lab

docker:
  compose:
    version: 1.23.1
    checksum: "sha256:c176543737b8aea762022245f0f4d58781d3cb1b072bc14f3f8e5bb96f90f1a2"
  repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  package: docker-ce
  users:
    - vagrant

beat:
  config:
    modules:
      reload:
        enabled: false
        period: 10s
  setup:
      dashboards:
        enabled: true
      kibana:
        host: utility.rz.lab:5601
        protocol: http
        username: elastic
        password: changeme
  output:
    elasticsearch:
      hosts:
        - utility.rz.lab:9200
      protocol: http
      username: elastic
      password: changeme
  filebeat:
    version: 6.4.3
    checksum: "sha256:0bcdb127760d1af54ccd0c76667dfc0983817c5f40c6c949235781a2292ae2b5"
    config_path: /etc/filebeat
  metricbeat:
    version: 6.4.3
    checksum: "sha256:3b4d3b309ca0cc13fed2ddcf40300cc67ffc726ca202a3dac7ace9b99520b77a"
    config_path: /etc/metricbeat
