---
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
ansible_python_interpreter: '/usr/bin/python2.7'
domain: rz.lab
dnsNameServers:
  - 10.100.10.1
username: vagrant
common:
  flags: /opt/ansible/flags

ldap:
  tld: lab
  org: rz
  directoryAdminPassword: Password1

slapd:
  installDaemon: false

ntp_area: 'us'
ntp_servers: 
  - ntp.rz.lab

netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses:
            - 10.100.10.1

systemd_resolved:
  disabled: true
  nameservers:
    - 10.100.10.1
  search_zones:
    - rz.lab

docker:
  compose:
    version: 1.23.1
    checksum: "sha256:c176543737b8aea762022245f0f4d58781d3cb1b072bc14f3f8e5bb96f90f1a2"
  repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  package: docker-ce
  users:
    - vagrant
  swarm:
    enabled: true
    node_type: manager

beat:
  config:
    modules:
      reload:
        enabled: false
        period: 10s
  setup:
      dashboards:
        enabled: true
      kibana:
        host: utility.rz.lab:5601
        protocol: http
        username: elastic
        password: changeme
  output:
    elasticsearch:
      hosts:
        - utility.rz.lab:9200
      protocol: http
      username: elastic
      password: changeme
  filebeat:
    version: 6.5.1
    checksum: "sha256:010f590ca8a672bcd018583547888f237b96438cc9c07bd6a80f4f8d2aec0db4"
    config_path: /etc/filebeat
  metricbeat:
    version: 6.5.1
    checksum: "sha256:729ed2cc19c6ed06a704f1aab91b2a2eb6267012303f7061544b6b59a70422a0"
    config_path: /etc/metricbeat


metricbeat:
  system:
    - module: system
      enabled: true
      period: 10s
      metricsets:
        - cpu             # CPU usage
        - load            # CPU load averages
        - memory          # Memory usage
        - network         # Network IO
        - process         # Per process metrics
        - process_summary # Process summary
        - uptime          # System Uptime
        #- core           # Per CPU core usage
        #- diskio         # Disk IO
        #- filesystem     # File system usage for each mountpoint
        #- fsstat         # File system summary metrics
        #- raid           # Raid
        #- socket         # Sockets and connection info (linux only)
      process:
        include_top_n:
          enabled: true
          by_cpu: 5      # include top 5 processes by CPU
          by_memory: 5   # include top 5 processes by memory

    - module: system
      enabled: true
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'