---
# defaults file for ansible-netplan
netplan_config_file:      /etc/netplan/config.yaml
netplan_remove_existing:  true
netplan_configuration:
  network:
    version: 2
    renderer: networkd
    ethernets:
      eth0:
        dhcp4: true
        dhcp6: false
        optional: true
        nameservers:
          addresses:
            - 1.1.1.1
            - 1.0.0.1
      eth1:
        dhcp4: false
        dhcp6: false
        addresses:
          - 10.100.10.1/24
        optional: true
        nameservers:
          addresses:
            - 127.0.0.1
          search:
            - rz.lab

dhcpdConf:
  option:
    domain_name: rz.lab
    domain_name_servers:
        - 10.100.10.1
  default_lease_time: 600  
  max_lease_time: 7200
  authoritative: true
  log_facility: local7
  subnets:
    - interface: eth1
      address: 10.100.10.1
      network: 10.100.10.0
      netmask: 255.255.255.0
      broadcast: 10.100.10.255
      range:
        - 10.100.10.100
        - 10.100.10.250
  hosts:
    - name: ansible_control_server
      mac_address: 00:35:10:00:01:00
      fixed_address: 10.100.10.2
    - name: utility_server
      mac_address: 00:35:10:00:01:01
      fixed_address: 10.100.10.3
    - name: directory_server
      mac_address: 00:35:10:00:01:02
      fixed_address: 10.100.10.4
    - name: swarm_master
      mac_address: 00:35:10:00:01:03
      fixed_address: 10.100.10.11
    - name: swarm_worker
      mac_address: 00:35:10:00:01:04
      fixed_address: 10.100.10.12

bind:
  forwarders:
    - 1.1.1.1
    - 1.0.0.1
  listen_on_v6:
    - none
  listen_on_v4:
    - 127.0.0.1
    - 10.100.10.1
  zones:
    - name: rz.lab
      TTL: 604800
      serial: 5
      refresh: 604800
      retry: 86400
      expire: 2419200
      negative_cache_ttl: 604800
      nameserver: router.rz.lab
      records:
        - name: router
          class: IN
          type: A
          target: 10.100.10.1
        - name: acs
          class: IN
          type: A
          target: 10.100.10.2
        - name: utility
          class: IN
          type: A
          target: 10.100.10.3
        - name: ntp
          class: IN
          type: CNAME
          target: utility
        - name: syslog
          class: IN
          type: CNAME
          target: utility
        - name: dc
          class: IN
          type: A
          target: 10.100.10.4

systemd_resolved:
  disabled: true
  nameservers:
    - 10.100.10.1
    - 1.1.1.1
    - 1.0.0.1
  search_zones:
    - rz.lab