---
- name: Download Metric Beat Package
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{beat.metricbeat.version}}-amd64.deb"
    dest: "/tmp/metricbeat-{{beat.metricbeat.version}}-amd64.deb"
    checksum: "{{beat.metricbeat.checksum}}"

- name: Install Metric Beat Package
  apt:
    deb: "/tmp/metricbeat-{{beat.metricbeat.version}}-amd64.deb"
    state: present

- name: Update metricbeat.yml configuration template.
  template:
    src: metricbeat.yml.j2
    dest: "{{beat.metricbeat.config_path}}/metricbeat.yml"

- name: Update system.yml module
  template:
    src: system.yml.j2
    dest: "{{beat.metricbeat.config_path}}/modules.d/system.yml"
  notify: 
    - Restart MetricBeat Service

- name: Enable and Start Metricbeat Service
  service:
    name: metricbeat
    state: started
    enabled: yes
  become: yes