---
- name: Ensure public docker network exists.
  docker_network:
    driver: overlay
    name: public
    state: present

- name: Ensure private docker network exists.
  docker_network:
    driver: overlay
    name: private
    state: present

- name: Add traefik directory.
  file:
    path: /opt/traefik
    state: directory

- name: Deploy Stack Config.
  template:
      src: traefik.stack.yml.j2
      dest: /opt/traefik/traefik.stack.yml
  notify: deploy traefik

- name: Ensure docker swarm is present.
  docker_swarm:
    state: present
    advertise_addr: "{{ansible_eth0.ipv4.address}}"
