---
bind:
  forwarders:
    - 1.1.1.1
    - 1.0.0.1
  listen_on_v6:
    - none
  listen_on_v4:
    - 127.0.0.1
    - 10.100.10.1
  zones:
    - name: rz.lab
      TTL: 604800
      serial: 1
      refresh: 604800
      retry: 86400
      expire: 2419200
      negative_cache_ttl: 604800
      records:
        - name: router
          class: IN
          type: A
          target: 10.100.10.1