---
- name: Add password authenticated user for gui access.
  user:
    name: "{{username}}"
    groups: sudo
    append: yes
    password: "{{password}}"
    uid: "{{uid}}"

- name: Install ca-certificates
  package:
    name: ca-certificates
    state: present

- name: Install curl
  package:
    name: curl
    state: present
