---

# Path to environment file
# Type: Str
sssd_environment_file: /etc/default/sssd

# Other FreeIPA modules are using pip to get the latest versions of the
# modules. Keep it consistent.
# Type: List
sssd_pip_dependency_pkgs:
  - dbus-python
  - pyasn1
  - pyasn1-modules
  - pyopenssl
  - python-ldap

# Add the sss pam module to the following nss databases
# Type: List
sssd_add_sss_to_nss_databases:
  - group
  - passwd
  - services
  - shadow
  - sudoers

# Empty dict
# Type: Dict
sssd_default_patches: {}

# It's not allowed to set the `sssd_user` to those values
# Type: List
sssd_forbidden_users:
  - adm
  - apache
  - backup
  - bin
  - bind
  - daemon
  - dbus
  - dirsrv
  - dnsmasq
  - ftp
  - games
  - gnats
  - halt
  - httpd
  - ipaapi
  - irc
  - kdcproxy
  - landscape
  - list
  - lp
  - lxd
  - mail
  - man
  - messagebus
  - news
  - nobody
  - nslcd
  - ntp
  - opendnssec
  - openldap
  - operator
  - pkiuser
  - polkitd
  - pollinate
  - proxy
  - root
  - shutdown
  - sshd
  - sync
  - sys
  - syslog
  - systemd-network
  - systemd-resolve
  - tomcat8
  - ubuntu
  - uucp
  - uuidd
  - vagrant
  - www-data

# Type: List
sssd_forbidden_groups: "{{ sssd_forbidden_users }}"
