---
- hosts: datacenter
  roles:
    - rz.common
    - rz.ssh_keys
    - mrlesmithjr.netplan
    - rz.ntp
    - rz.syslog
    - rz.disable_systemd_resolved

- hosts: routers
  roles:
    - rz.router
    - rz.bind
