---
- name: Install DHCP Server
  package:
    name: isc-dhcp-server
    state: present
  become: yes

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: True
  become: yes

- name: Configure interfaces DHCP Server will listen on.
  template:
    src:  "isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"
  become: yes
  notify: restart isc-dhcp-server

- name: Configure Subnets hosted by the DHCP Server
  template:
    src:  "dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
  become: yes
  notify: restart isc-dhcp-server

- name: Enable and Start DHCP Server
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
  become: yes

- name: Include IPV4 Firewall Rule tasks
  include_tasks: ipv4.yml

- name: 'Include firewall port 80 foward to docker-manager.'
  include_tasks: allow_port_80_to_docker-manager.yml

- name: Include IPV6 Firewall Rule tasks
  include_tasks: ipv6.yml

- name: Enable ICMP Type 8
  include_tasks: enable_ICMP_type_8.yml