---
- name: Set /etc/network/interfaces.
  template:
    src:  "interfaces.j2"
    dest: "/etc/network/interfaces"
  notify: restart networking service

- name: Install isc-dhcp-server
  package:
    name: isc-dhcp-server
    state: present

- name: Set /etc/default/isc-dhcp-server.
  template:
    src:  "isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"
  notify: restart isc-dhcp-server

- name: Set /etc/dhcp/dhcpd.conf.
  template:
    src:  "dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
  notify: restart isc-dhcp-server

- name: Enable and Start isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
