---
- name: Install DHCP Server
  package:
    name: isc-dhcp-server
    state: present
  become: yes

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True
  become: yes

- name: Configure interfaces DHCP Server will listen on.
  template:
    src:  "isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"
  become: yes
  notify: restart isc-dhcp-server

- name: Configure Subnets hosted by the DHCP Server
  template:
    src:  "dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
  become: yes
  notify: restart isc-dhcp-server

- name: Enable and Start DHCP Server
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes
  become: yes

- name: Accept incoming packets from localhost interface
  iptables:
    table: filter
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: Ansible[router] - Accept incoming packets from localhost interface
  become: yes
  notify:
    - persist iptables

- name: Accept incoming packets from LAN interface
  iptables:
    table: filter
    chain: INPUT
    in_interface: eth1
    jump: ACCEPT
    comment: Ansible[router] - Accept incoming packets from LAN interface
  become: yes
  notify:
    - persist iptables

- name: Accept incoming packets from the WAN if the router initiated the connection
  iptables:
    table: filter
    chain: INPUT
    in_interface: eth0
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Ansible[router] - Accept incoming packets from the WAN if the router initiated the connection
  become: yes
  notify:
    - persist iptables

- name: Forward LAN packets to the WAN
  iptables:
    table: filter
    chain: FORWARD
    in_interface: eth1
    out_interface: eth0
    jump: ACCEPT
    comment: Ansible[router] - Forward LAN packets to the WAN
  become: yes
  notify:
    - persist iptables

- name: Forward WAN packets to the LAN if the LAN initiated the connection
  iptables:
    table: filter
    chain: FORWARD
    in_interface: eth0
    out_interface: eth1
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Ansible[router] - Forward WAN packets to the LAN if the LAN initiated the connection
  become: yes
  notify:
    - persist iptables

- name: Accept new SSH Connections.
  iptables:
    chain: INPUT
    protocol: tcp
    source: 172.28.14.0/24
    destination_port: 22
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Ansible[router] - Accept new SSH connections.
  become: yes
  notify:
    - persist iptables

- name: Create Iptables NAT chain
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
    comment: Ansible[router] - NAT Masquerade
  become: yes
  notify:
    - persist iptables

- name: Default policy to drop all incoming ipv4 packets
  iptables:
    table: filter
    chain: INPUT
    policy: DROP
    comment: Ansible[router] - Default policy to drop all incoming ipv4 packets
  become: yes
  notify:
    - persist iptables


- name: Default policy to drop all forwarded ipv4 packets
  iptables:
    table: filter
    chain: FORWARD
    policy: DROP
    comment: Ansible[router] - Default policy to drop all forwarded ipv4 packets
  become: yes
  notify:
    - persist iptables

