---
- name: Install DHCP Server
  package:
    name: isc-dhcp-server
    state: present

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True

- name: Configure interfaces DHCP Server will listen on.
  template:
    src:  "isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"
  notify: restart isc-dhcp-server

- name: Configure Subnets hosted by the DHCP Server
  template:
    src:  "dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
  notify: restart isc-dhcp-server

- name: Enable and Start DHCP Server
  service:
    name: isc-dhcp-server
    state: started
    enabled: yes

- name: Accept incoming packets from localhost interface
  iptables:
    table: filter
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Accept incoming packets from LAN interface
  iptables:
    table: filter
    chain: INPUT
    in_interface: eth1
    jump: ACCEPT

- name: Accept incoming packets from the WAN if the router initiated the connection
  iptables:
    table: filter
    chain: INPUT
    in_interface: eth0
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Forward LAN packets to the WAN
  iptables:
    table: filter
    chain: FORWARD
    in_interface: eth1
    out_interface: eth0
    jump: ACCEPT

- name: Forward WAN packets to the LAN if the LAN initiated the connection
  iptables:
    table: filter
    chain: FORWARD
    in_interface: eth0
    out_interface: eth1'
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Accept new SSH Connections.
  iptables:
    chain: INPUT
    protocol: tcp
    source: 172.28.14.0/24
    destination_port: 22
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Accept new SSH connections.

- name: Create Iptables NAT chain
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
    comment: Ansible NAT Masquerade

- name: Default policy to drop all incoming packets
  iptables:
    table: filter
    chain: INPUT
    policy: DROP

- name: Default policy to drop all forwarded packets
  iptables:
    table: filter
    chain: FORWARD
    policy: DROP
