# frozen_string_literal: true
vagrant_api_version = '2'

hyperv_network = 'Internet'

machines = {
  jdk: {
    box: 'gusztavvargadr/ubuntudesktop16',
    cpus: 2,
    mem: 2048,
    vmname: 'jdk',
    mac: '00:35:10:01:00:02',
  },
}

Vagrant.configure(vagrant_api_version) do |config|
  machines.each do |hostname, info|
    config.vm.define hostname do |machine|
      machine.vm.box = info[:box]
      machine.vm.hostname = hostname
      machine.vm.network 'public_network', bridge: hyperv_network
      machine.vm.provider 'hyperv' do |hv|
        hv.vmname = info[:vmname]
        hv.memory = info[:mem]
        hv.cpus = info[:cpus]
        hv.mac = info[:mac]
      end
      machine.vm.provision 'shell',
        inline: 'sudo apt-get update && apt-get install python2.7 -y'
    end
  end
end
