---
- name: Add a new user
  user:
    name: "{{username}}"

- name: Add user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{username}}"
    content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key:
    user: "{{username}}"
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    state: present

- name: Apply sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh
