---
rsyslog_remote_template_file: /etc/rsyslog.d/tmpl.conf
rsyslog_logrotate_conf_file: /etc/logrotate.d/rsyslog

rsyslog_modules:
  - imuxsock
  - imklog
  - imudp
  - imtcp

rsyslog_inputs:
  - type: imtcp
    port: 514
  - type: imudp
    port: 514
