---
slapd:
  packages:
    - ldap-utils
    - slapd
  tld: lab
  org: rz
  olcLogLevel: stats
  inetOrgPersons:
    - username: joeSchmoe
      surname: Schmoe
      givenName: Joe
      password: Password1
  posixGroups:
    - name: ldapUsers
      gid: 4000
  posixUsers:
    - username: jdoe
      surname: Doe
      givenName: John
      password: Password1
      uid: 5000
      gid: 4000
      shell: /bin/bash
  debconf:
    backend: MDB
    default_admin_password: password
    domain: rz.lab
    dump_database: when needed
    dump_database_destdir: /var/backups/slapd-VERSION
    invalid_config: true
    move_old_database: true
    organization: rz
    no_configuration: false
    ppolicy_schema_needs_update: abort installation
    purge_database: false
