---
username: vagrant
ssh_key_path: /home/vagrant/.ssh/id_rsa
rke_version: v0.1.9
rke_binary: rke_linux-amd64
rke_sha256sum: ab2d37431b1bb88d86b79ecb507def2e7a1be7bd50b58246aa9d152f5ea657de

rke_nodes:
  - address: "{{hostvars['rancher1']['ansible_default_ipv4']['address']}}"
    roles:
      - "controlplane"
      - "worker"
      - "etcd"
  - address: "{{hostvars['rancher2']['ansible_default_ipv4']['address']}}"
    roles:
      - "controlplane"
      - "worker"
      - "etcd"
  - address: "{{hostvars['rancher3']['ansible_default_ipv4']['address']}}"
    roles:
      - "controlplane"
      - "worker"
      - "etcd"