---
beat:
  config:
    modules:
      reload:
        enabled: false
        period: 10s
  setup:
      dashboards:
        enabled: true
      kibana:
        host: utility.rz.lab:5601
        protocol: http
        username: elastic
        password: changeme
  output:
    elasticsearch:
      hosts:
        - utility.rz.lab:9200
      protocol: http
      username: elastic
      password: changeme
  metricbeat:
    version: 6.4.3
    checksum: "sha256:3b4d3b309ca0cc13fed2ddcf40300cc67ffc726ca202a3dac7ace9b99520b77a"
    config_path: /etc/metricbeat

metricbeat:
  system:
    enabled: true
    syslog:
      enabled: true
      var:
        paths: []
        convert_timezone: false
    auth:
      enabled: true
      var:
        paths: []
        convert_timezone: false