galaxy_info:
  author:               Larry Smith Jr.
  description:          An [Ansible](https://www.ansible.com) role to manage [Netplan](https://netplan.io)

  license:              license (GPLv2, CC-BY, etc)

  min_ansible_version:  1.2

  platforms:
    - name:             Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - networking

dependencies:           []
