---
- name: Install bind9
  package:
    name: bind9
    state: present

- name: Apply named.conf.options configuration.
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: "Apply db.{{item.name}} configuration."
  template:
    src: db.zone.j2
    dest: "/etc/bind/db.{{item.name}}"
  with_items: "{{bind.zones}}"