---
wanInterface: eth0

dnsNameServers:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4

dhcpdConf:
  option:
    domain_name: rz.lab
    domain_name_servers:
        - 1.1.1.1
        - 8.8.8.8
  default_lease_time: 600  
  max_lease_time: 7200
  authoritative: true
  log_facility: local7
  subnets:
    - interface: eth1
      address: 10.100.10.1
      network: 10.100.10.0
      netmask: 255.255.255.0
      broadcast: 10.100.10.255
      range:
        - 10.100.10.100
        - 10.100.10.250
