---
beat:
  version: 6.4.3
  checksum: "sha256:0bcdb127760d1af54ccd0c76667dfc0983817c5f40c6c949235781a2292ae2b5"
  filebeat:
    config:
      modules:
        path: modules.d/*.yml
        reload:
          enabled: true
          period: 10s
    output:
      elasticsearch:
        hosts:
          - utility.rz.lab:9200
        protocol: http
        username: elastic
        password: changeme
  apache2:
    enabled: false
    access:
      enabled: true
      var.paths: []
    error:
      enabled: true
      var.paths: []
  system:
    enabled: true
    syslog:
      enabled: true
      var:
        paths: []
        convert_timezone: false
    auth:
      enabled: true
      var:
        paths: []
        convert_timezone: false