---
- name: Check for configure flag
  stat:
    path: "{{common.flags}}/ldap.installed"
  register: stat_result

- name: Answer slapd install questions
  debconf:
    name: ldap-auth-config
    question: "{{item.question}}"
    value: "{{item.value}}"
    vtype: "{{item.vtype}}"
  loop:
    - question: ldap-auth-config/rootbindpw
      value: "{{ldap.directoryAdminPassword}}"
      vtype: password
    - question: ldap-auth-config/bindpw
      value: "{{ldap.directoryAdminPassword}}"
      vtype: password
    - question: ldap-auth-config/rootbinddn
      value: "cn=admin,dc={{ldap.org}},dc={{ldap.tld}}"
      vtype: string
    - question: ldap-auth-config/dbrootlogin
      value: "true"
      vtype: boolean
    - question: ldap-auth-config/ldapns/base-dn
      value: "dc={{ldap.org}},dc={{ldap.tld}}"
      vtype: string
    - question: ldap-auth-config/binddn
      value: "cn=admin,dc={{ldap.org}},dc={{ldap.tld}}"
      vtype: string
    - question: ldap-auth-config/ldapns/ldap_version
      value: "3"
      vtype: select
    - question: ldap-auth-config/pam_password
      value: "md5"
      vtype: select
    - question: ldap-auth-config/dblogin
      value: "false"
      vtype: boolean
    - question: ldap-auth-config/ldapns/ldap-server
      value: "ldap://dc.{{ldap.org}}.{{ldap.tld}}"
      vtype: string
    - question: ldap-auth-config/override
      value: "true"
      vtype: boolean
    - question: ldap-auth-config/move-to-debconf
      value: "true"
      vtype: boolean
  when: stat_result.stat.exists == false

- name: Install LDAP Packages
  package:
    name: libnss-ldap
    state: present

- name: add install flag
  copy:
    content: ""
    dest: "{{common.flags}}/ldap.installed"
    force: no
    owner: root
    group: root
    mode: "u=rw,g=rw,o=r"
