---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install Fail2ban
  package:
    name: fail2ban
    state: present

- name: install iptables-persistent
  package: 
    name: iptables-persistent
    state: present

- name: Set hostname
  hostname:
    name: "{{hostname}}.{{domain}}"

- name: Set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  become: yes

- name: Create Flags Directory
  file:
    name: "{{common.flags}}"
    state: directory

- name: Disable RFC 1323 to mitigate leakage of uptime information.
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: '0'
    state: present
    reload: True
  become: yes
