---

galaxy_info:
  author: Timo Runge
  company: N/A
  description: Custom SSSD installation and configuration including patch management for the SSSD source.
  role_name: sssd
  license: BSD-3-Clause
  min_ansible_version: 2.6.0
  platforms:
  - name: EL
    versions:
      - 7
  - name: Debian
    versions:
      - stretch
      - buster
  - name: Fedora
    versions:
      - 26
      - 27
      - 28
  - name: Ubuntu
    versions:
      - trusty
      - xenial
      - artful
      - bionic
      - cosmic
  galaxy_tags:
    - authorization
    - compile
    - sssd
    - system
dependencies: []
