---

- name: Install SSSD packages
  package:
    name: "{{ sssd_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
