---
- name: Download File Beat Package
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{beat.version}}-amd64.deb"
    dest: "/tmp/filebeat-{{beat.version}}-amd64.deb"
    checksum: "{{beat.checksum}}"

- name: Install File Beat Package
  apt:
    deb: "/tmp/filebeat-{{beat.version}}-amd64.deb"
    state: present

- name: Update filebeat.yml configuration template.
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
