---
- name: Download File Beat Package
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{file_beat.version}}-amd64.deb"
    dest: "/tmp/filebeat-{{file_beat.version}}-amd64.deb"
    checksum: "{{file_beat.checksum}}"

- name: Install File Beat Package
  apt:
    deb: "/tmp/filebeat-{{file_beat.version}}-amd64.deb"
    state: present
