---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    - name: Ensure 'man' directory exists.
      file:
        path: /usr/share/man/man1
        state: directory
        recurse: true
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_version == '18.04'

  roles:
    - role: geerlingguy.java
