---

- name: Install SSSD build dependencies
  package:
    name: "{{ sssd_build_dependency_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"

- name: Install SSSD pip dependencies
  pip:
    name: "{{ sssd_pip_dependency_pkgs }}"
    state: present

- name: Create SSSD group
  group:
    name: "{{ sssd_group }}"
    state: present
  when: sssd_group not in sssd_forbidden_groups

- name: Create SSSD user
  user:
    create_home: no
    groups: "{{ sssd_group }}"
    home: /var/lib/sss
    name: "{{ sssd_user }}"
    shell: /usr/sbin/nologin
  when: sssd_group not in sssd_forbidden_users

- name: Create directories
  file:
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
    owner: "{{ item.value.owner }}"
    path: "{{ item.key }}"
    state: directory
  loop: "{{ (sssd_dirs | combine(sssd_additional_dirs)) | dict2items }}"
