---

- name: Patch SSSD source
  patch:
    dest: "{{ sssd_install_dir }}/build/sssd-sssd-{{ sssd_version_src_schema }}/{{ item.value.dest_file }}"
    src: "{{ item.value.patch_file }}"
    state: "{{ item.value.state | default(present) }}"
  loop: "{{ sssd_patches | dict2items }}"
  register: sssd_patches
  when: sssd_patches
