---
- hosts: datacenter
  roles:
    - rz.ntp
    - mrlesmithjr.netplan
    - rz.disable_systemd_resolved
    - rz.common
    - rz.ssh_keys
    - rz.certs

- hosts: directory_servers
  roles:
    - rz.slapd

- hosts: datacenter
  roles:
    - rz.sssd

- hosts: utility_servers
  gather_facts: true
  roles:
    - rz.docker
    - rz.elastic_stack

- hosts: routers
  roles:
    - rz.router
    - rz.bind

- hosts: docker_swarm_managers
  gather_facts: true
  roles:
    - rz.docker