---
- hosts: datacenter
  roles:
    - rz.common
    - rz.ssh_keys
    - mrlesmithjr.netplan
    - rz.ntp
    - rz.syslog
    - rz.disable_systemd_resolved

- hosts: routers
  roles:
    - rz.router
    - rz.bind

- hosts: utility_servers
  gather_facts: true
  roles:
    - rz.docker
    - rz.elastic_stack
    - rz.elastic_stack.file_beat