---
- name: Remove docker
  package:
    name: docker
    state: absent

- name: Remove docker-engine
  package:
    name: docker-engine
    state: absent

- name: Remove docker.io
  package:
    name: docker.io
    state: absent

- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: present

- name: Install ca-certificates
  package:
    name: ca-certificates
    state: present

- name: Install curl
  package:
    name: curl
    state: present

- name: Install software-properties-common
  package:
    name: software-properties-common
    state: present

- name: Get Docker's official GPG key
  apt_key :
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE Stable Repository
  apt_repository:
    repo: "{{docker.repository}}"
    state: present

- name: Install docker-ce
  package:
    name: "{{docker.package}}"
    state: present

- name: Add user to docker group.
  user:
    name: "{{item}}"
    groups: docker
    append: yes
  with_items: docker.users

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker.compose.version}}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
    checksum: "{{docker.compose.checksum}}"

- name: Install python-pip
  package:
    name: python-pip
    state: present

- name: Install docker python module.
  pip:
    name: docker
    state: present